version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app1:
    build:
      context: ./server
    container_name: app1
    environment:
      - SERVER_ID=app1
      - SPRING_REDIS_HOST=redis
    expose:
      - "8080"

  app2:
    build:
      context: ./server
    container_name: app2
    environment:
      - SERVER_ID=app2
      - SPRING_REDIS_HOST=redis
    expose:
      - "8080"

  app3:
    build:
      context: ./server
    container_name: app3
    environment:
      - SERVER_ID=app3
      - SPRING_REDIS_HOST=redis
    expose:
      - "8080"

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "8088:80"      # client connects to localhost:8088
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - redis
